# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy On Nginx

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - run: rm -rf /home/leekyusung/nginx-root/nomad-kokoa-clone
      - run: cp -r . /home/leekyusung/nginx-root/nomad-kokoa-clone
